create extension if not exists citext;

create table if not exists public.usuarios (
    id bigint generated by default as identity primary key,
    nome text not null,
    email citext not null,
    senha text not null,
    hierarquia text not null default 'normal',
    status text not null default 'ativo',
    senha_temporaria boolean not null default false,
    logged_in boolean not null default false,
    equipe_id bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint usuarios_email_key unique (email),
    constraint usuarios_hierarquia_check check (hierarquia in ('admin', 'normal', 'staff', 'rh')),
    constraint usuarios_status_check check (status in ('ativo', 'inativo'))
);

create table if not exists public.equipes (
    id bigint generated by default as identity primary key,
    nome_equipe text not null,
    supervisor_id bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint equipes_nome_equipe_key unique (nome_equipe)
);

create table if not exists public.escalas (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null,
    dia_semana text not null,
    entrada time,
    pausa time,
    volta_pausa time,
    saida time,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint escalas_dia_semana_check check (
        dia_semana in ('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo')
    ),
    constraint escalas_usuario_dia_key unique (usuario_id, dia_semana)
);

create table if not exists public.jornadas (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null,
    jornada_esperada interval not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint jornadas_usuario_key unique (usuario_id)
);

create table if not exists public.ponto (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null,
    data_registro date not null,
    hora_registro time not null,
    tipo text not null,
    abonado boolean not null default false,
    motivo_abono text,
    corrigido boolean not null default false,
    hora_corrigida time,
    motivo_correcao text,
    corrigido_por bigint,
    data_hora_alteracao timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ponto_tipo_check check (tipo in ('entrada', 'pausa', 'volta_pausa', 'saida')),
    constraint ponto_usuario_data_tipo_key unique (usuario_id, data_registro, tipo)
);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'usuarios_equipe_id_fkey'
    ) then
        alter table public.usuarios
            add constraint usuarios_equipe_id_fkey
            foreign key (equipe_id)
            references public.equipes (id)
            on delete set null
            deferrable initially deferred;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'equipes_supervisor_id_fkey'
    ) then
        alter table public.equipes
            add constraint equipes_supervisor_id_fkey
            foreign key (supervisor_id)
            references public.usuarios (id)
            on delete set null
            deferrable initially deferred;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'escalas_usuario_id_fkey'
    ) then
        alter table public.escalas
            add constraint escalas_usuario_id_fkey
            foreign key (usuario_id)
            references public.usuarios (id)
            on delete cascade
            deferrable initially deferred;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'jornadas_usuario_id_fkey'
    ) then
        alter table public.jornadas
            add constraint jornadas_usuario_id_fkey
            foreign key (usuario_id)
            references public.usuarios (id)
            on delete cascade
            deferrable initially deferred;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'ponto_usuario_id_fkey'
    ) then
        alter table public.ponto
            add constraint ponto_usuario_id_fkey
            foreign key (usuario_id)
            references public.usuarios (id)
            on delete cascade
            deferrable initially deferred;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'ponto_corrigido_por_fkey'
    ) then
        alter table public.ponto
            add constraint ponto_corrigido_por_fkey
            foreign key (corrigido_por)
            references public.usuarios (id)
            on delete set null
            deferrable initially deferred;
    end if;
end
$$;

create index if not exists idx_usuarios_equipe_id on public.usuarios (equipe_id);
create index if not exists idx_usuarios_hierarquia on public.usuarios (hierarquia);
create index if not exists idx_usuarios_status on public.usuarios (status);
create index if not exists idx_equipes_supervisor_id on public.equipes (supervisor_id);
create index if not exists idx_escalas_usuario_id on public.escalas (usuario_id);
create index if not exists idx_ponto_usuario_data on public.ponto (usuario_id, data_registro);
create index if not exists idx_ponto_data_registro on public.ponto (data_registro);
create index if not exists idx_ponto_corrigido_por on public.ponto (corrigido_por);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_updated_at_usuarios on public.usuarios;
create trigger set_updated_at_usuarios
before update on public.usuarios
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_equipes on public.equipes;
create trigger set_updated_at_equipes
before update on public.equipes
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_escalas on public.escalas;
create trigger set_updated_at_escalas
before update on public.escalas
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_jornadas on public.jornadas;
create trigger set_updated_at_jornadas
before update on public.jornadas
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_ponto on public.ponto;
create trigger set_updated_at_ponto
before update on public.ponto
for each row
execute function public.set_updated_at();
